### ISSUE TITLE
[BUG] The Bot tags me on vtubers that I didn't choose right after one that I did choose.

### ISSUE THREAD

**Issue by luijaro** [JustHumanz/Go-Simp#127]
The Bot tags me on vtubers that I didn't choose right after one that I did choose.

I have the following sample images.

It should be noted that the three publications were made at the same time and I wanted him to notify me only by Saki-chan, maybe the time can be the problem.

![1](https://user-images.githubusercontent.com/22866388/108572495-2ba74780-72f1-11eb-874e-d42682479ccd.png)
![2](https://user-images.githubusercontent.com/22866388/108572499-2c3fde00-72f1-11eb-89a2-799bf55d5ee6.png)

**Comment by JustHumanz** [comment]
hi,thx for your reporting

ah for this issues,some member on discord already realized this bug ,and i already add [patch](https://github.com/JustHumanz/Go-Simp/commit/5bc208878ad33708e65a7814b397ea84eab20c67) for this issues

let me know if these issues still happening

**Comment by luijaro** [comment]
Thanks for the reply.

I will be watching and I will let you know if it happens again.
