### ISSUE TITLE
Add Ciyana from independent

### ISSUE THREAD

**Issue by ghost** [JustHumanz/Go-Simp#163]
{
    "Name": "Ciyana",
    "EN_Name": "Ciyana",
    "JP_Name": "",
    "Twitter":{
        "Twitter_Fanart": "",
        "Twitter_Lewd": "",
        "Twitter_Username": "_ciyana"
    },
    "Youtube":{
        "Yt_ID": ""
    },
    "BiliBili":{
        "BiliBili_Fanart": {BiliBili Fanart hashtag},
        "BiliBili_ID": 1926156228,
        "BiliRoom_ID": 22608112
    },
    "Twitch":{
        "Twitch_Username": ""
    },
    "Region": "CN",
    "Fanbase": ""
},

Example :

{
    "Name":"Kanochi",
    "EN_Name":"Kano",
    "JP_Name":"鹿乃",
    "Twitter":{
        "Twitter_Fanart":"#絵えかの",
        "Twitter_Lewd":"",
        "Twitter_Username":"kanolive_"
    },
    "Youtube":{
        "Yt_ID":"UCfuz6xYbYFGsWWBi3SpJI1w"
    },
    "BiliBili":{
        "BiliBili_Fanart":"鹿乃絵",
        "BiliBili_ID":316381099,
        "BiliRoom_ID":15152878
    },
    "Twitch":{
        "Twitch_Username":""
    },
    "Region":"JP",
    "Fanbase":""
},

**Comment by JustHumanz** [comment]
hy,i'm just research about Ciyana and i found #希梦思# hashtag
it's like that was fanart hashtag

**Comment by JustHumanz** [comment]
done,see at [here](https://github.com/JustHumanz/Go-Simp/releases/tag/v3.6.1)
