### ISSUE TITLE
Add Azulim from Independent

### ISSUE THREAD

**Issue by ltsc1980** [JustHumanz/Go-Simp#193]
{
    "Name": "Azulim",
    "EN_Name": "Azuma Lim",
    "JP_Name": "アズマリム",
    "Twitter":{
        "Twitter_Fanart":"#azulimart",
        "Twitter_Lewd":,
        "Twitter_Username":"@azuma_lim"
    },
    "Youtube":{
        "Yt_ID": "UCARI2g7r-PHaxrIcAYsMfmA"
    },
    "BiliBili":{
        "BiliBili_Fanart": ,
        "BiliBili_ID": ,
        "BiliRoom_ID": 
    },
    "Twitch":{
        "Twitch_Username": 
    },
    "Region": "JP",
    "Fanbase": 
},

**Comment by JustHumanz** [comment]
3875ca86c816138a635f457afb00ec7275ec665a
