### ISSUE TITLE
Add Voice-ore

### ISSUE THREAD

**Issue by ltsc1980** [JustHumanz/Go-Simp#205]
https://virtualyoutuber.fandom.com/wiki/VOICE-ORE

**Comment by JustHumanz** [comment]
Can you help me to add the voice ore data?

Name = ""
EN_Name = ""
JP_Name = ""
Region = ""
FanbaseName = ""

[Twitter]
Twitter_Fanart = ""
Twitter_Lewd = ""
Twitter_Username = ""

[Youtube]
Yt_ID = ""

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""

**Comment by ltsc1980** [comment]
Name = "Rena"
EN_Name = "Shiratori Rena"
JP_Name = "白鳥怜奈"
Region = "JP"
FanbaseName = "Renavants"

[Twitter]
Twitter_Fanart = "れなーぶる"
Twitter_Lewd = ""
Twitter_Username = "shiratori_rena_"

[Youtube]
Yt_ID = "UCL4UZHX-26xAtVT4Jys5A1Q"

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""

**Comment by ltsc1980** [comment]
Name = "Kogane"
EN_Name = "Himukai Kogane"
JP_Name = "日向こがね"
Region = "JP"
FanbaseName = ""

[Twitter]
Twitter_Fanart = "5000兆絵ん欲しい"
Twitter_Lewd = ""
Twitter_Username = "himukai_kogane_"

[Youtube]
Yt_ID = "UCQgi2mK2f9l0Dky2-YhVTYQ"

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""

**Comment by ltsc1980** [comment]
Name = "Mizuki"
EN_Name = "Aoi Mizuki"
JP_Name = "蒼井美月"
Region = "Mizuki"
FanbaseName = ""

[Twitter]
Twitter_Fanart = "美月見"
Twitter_Lewd = ""
Twitter_Username = "aoi_mizuki__"

[Youtube]
Yt_ID = "UCupxrBQzU803Gzm05ECJffw"

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""

**Comment by ltsc1980** [comment]
Name = "Momo"
EN_Name = "Aizawa Momo"
JP_Name = "藍沢もも"
Region = "JP"
FanbaseName = ""

[Twitter]
Twitter_Fanart = "絵ももも"
Twitter_Lewd = ""
Twitter_Username = "aizawa_momo_"

[Youtube]
Yt_ID = "UCYQgNMUfReVWZspzSSexMGQ"

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""


Name = "Saki"
EN_Name = "Asagi Saki"
JP_Name = "浅葱サキ"
Region = "JP"
FanbaseName = ""

[Twitter]
Twitter_Fanart = "浅葱図録"
Twitter_Lewd = ""
Twitter_Username = "asagi_saki_"

[Youtube]
Yt_ID = "UCZ2rFJTs3IPJzYfxtvbKp8Q"

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""

Name = "Rin"
EN_Name = "Sumirezaki Rin"
JP_Name = "菫崎リン"
Region = "JP"
FanbaseName = ""

[Twitter]
Twitter_Fanart = "みてすみリン"
Twitter_Lewd = "罪リン"
Twitter_Username = "sumirezaki_rin"

[Youtube]
Yt_ID = "UCymJsbvAMc3j-bcsoxI7NZQ"

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""

**Comment by JustHumanz** [comment]
Great

**Comment by JustHumanz** [comment]
Done
you can check it in [here](https://go-simp.humanz.moe/#/group/28)

**Comment by ltsc1980** [comment]
New Member

Name = "BenikabaSakura"
EN_Name = "Benikaba Sakura"
JP_Name = "紅樺さくら"
Region = "JP"
FanbaseName = ""

[Twitter]
Twitter_Fanart = "さくらすけっち"
Twitter_Lewd = "紅色リップ"
Twitter_Username = "benikaba_sakura"

[Youtube]
Yt_ID = "UCsvLzyduqA3GZC7cBRixxRg"

[BiliBili]
BiliBili_Fanart = ""
BiliBili_ID = ""
BiliRoom_ID = ""

[Twitch]
Twitch_Username = ""
