### ISSUE TITLE
[BUG] fanart not show to some agency

### ISSUE THREAD

**Issue by futag** [JustHumanz/Go-Simp#248]
**Describe the bug**
In "Yume Reality", i can't find fanart in this agency

**Expected behavior**
Some new agency added not showing fanart

**Comment by JustHumanz** [comment]
i think it's happened because `Yume Reality` don't have any fanart in pixiv or my scrapper can't get it from pixiv

by default, if you use `art` command bot will [randomly](https://github.com/JustHumanz/Go-Simp/blob/master/pkg/database/fanart.go#L85) pick fanart from `twitter` `pixiv` or `bilibili`

**Comment by JustHumanz** [comment]
Already [fixed](4dd0198accc9ca80004fdc7ec8f08b3290b44069)
