### ISSUE TITLE
[BUG] Rena Anggraeni not show in migrate/group

### ISSUE THREAD

**Issue by futag** [JustHumanz/Go-Simp#249]
**Describe the bug**
Rena Anggraeni not show in database maha5

**Expected behavior**
Her live schedule and fan art disturbed

**Screenshots**
![image](https://user-images.githubusercontent.com/21020026/152680171-5f825054-eee1-4086-8fa7-66d1c2305fe9.png)

**Comment by JustHumanz** [comment]
`Penyihir` already added


![Screenshot 2022-02-08 at 10-56-42 Go-Simp](https://user-images.githubusercontent.com/43176061/152915458-ff9c72df-759f-4973-b861-ceabfe567fb3.png)
