### ISSUE TITLE
Some planing today

### ISSUE THREAD

**Issue by futag** [JustHumanz/Go-Simp#262]
- Change a disband group (ENTUM -> IRIAM) and moving some left members
- Change **Virtual Diva AZKi** to simply **AZKi**
- Deactivated Lee Siu (20 March) and Ko Yami

**Comment by JustHumanz** [comment]
point no 3 was sad :"(

**Comment by JustHumanz** [comment]
for point no 1,i don't find any news or reference for ENTHUM is move into IRIAM
but i found out if ENTUM closing down and some of the members was still continuing Livestream

![Screenshot 2022-02-22 at 12-20-08 Nekomiya Hinata](https://user-images.githubusercontent.com/43176061/155067947-9082dafd-89ee-45ab-ba18-d4003d21913b.png)

[source](https://virtualyoutuber.fandom.com/wiki/Nekomiya_Hinata?commentId=4400000000000010504&replyId=4400000000000019143)

So i think we need to remove ENTUM and move Mirai and Hinata to indie

**Comment by futag** [comment]
so, mirai move parent from ENTUM (ZIZAI aka DUO Inc)
https://virtualyoutuber.fandom.com/wiki/Mirai_Akari
https://virtualyoutuber.fandom.com/wiki/ZIZAI

**Comment by JustHumanz** [comment]
i think no,just found some commnet say mirai move into goomstudio

![Screenshot 2022-02-22 at 18-34-24 Mirai Akari](https://user-images.githubusercontent.com/43176061/155124370-48d4ef5a-63c9-456e-98a7-d8a54207fd43.png)

and it was confirmed by mirai twitter

![Screenshot from 2022-02-22 18-36-47](https://user-images.githubusercontent.com/43176061/155124733-379dae98-ad51-4a32-b5da-fe84de47ca57.png)

**Comment by JustHumanz** [comment]
### TODO

- [x] Create goom studio
- [x] Move akari into goom studio
