### ISSUE TITLE
TO DO LIST after completed web

### ISSUE THREAD

**Issue by futag** [JustHumanz/Go-Simp#263]
- [x] optimize code
- [x] some tweak look
- [x] add sort from followers
- [x] add dark mode

**Comment by JustHumanz** [comment]
optimize code can be later,can running is first

it's ready to deploy right now?

**Comment by futag** [comment]
![Untitled-1](https://user-images.githubusercontent.com/21020026/155251676-c8aee3b1-faeb-419e-84e9-1a8dc0958f30.png)
i have plan for make list like this

**Comment by JustHumanz** [comment]
owh ok,just let me know if you need something from backend api
