### ISSUE TITLE
[BUG] After VTbot is kicked off the server and invited to the same server again, VTbot no longer accepts command line input

### ISSUE THREAD

**Issue by HalfMAI** [JustHumanz/Go-Simp#286]
**Describe the bug**
After VTbot is kicked off the server and invited to the same server again, VTbot no longer accepts command line input

**Expected behavior**
VTbot can accepts command

**Screenshots**
![image](https://user-images.githubusercontent.com/5293796/164143249-1796dbda-1dbe-4890-b590-dcac12e8d80b.png)

**Additional context**

Reproduction steps
1. Create a private server
2. Invite VTBot->do not change any permission settings
3. Test if command line is available -> normally available
4. Cancel integration or kick VTBot
5. Invite VTBot again -> do not change any permission settings
6. Test if command line is available -> command line will not show VTBot's commands

**Comment by JustHumanz** [comment]
i already restart the guild service, the bot should register the slash command on all guilds pls check it

**Comment by HalfMAI** [comment]
Thank you for your reply.
I re-tested on the old server and VTBot still does not work with the Slash command, what more information do I need to provide to help solve the problem?

**Comment by JustHumanz** [comment]
still investigating this bug, still have no clue what actually the root cause 

btw thx for reporting the bug, very appreciated

**Comment by JustHumanz** [comment]
The bug already fixed in bed23fbe120da66e21269828c3e1953d6daea8f8

**Comment by HalfMAI** [comment]
I re-tested on the old server;
Test passed

Test on the new server;
Test passed

Confirmed the problem is fixed, thanks
