### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by zuramai** [JustHumanz/Go-Simp#290]
Hi, 
Do you have any guide how to contribute to this project? I'm not a Go developer, but I think I can contribute into the frontend (Vue) project.

I guess it's better if we have a contributing guide, from the local installation to making a pull request. 

Regards

**Comment by JustHumanz** [comment]
for guide not yet, previously the web already rebased by @yarndinasti 
but yeah if you two can collaborate it's will be great

**Comment by JustHumanz** [comment]
let me create the CONTRIBUTING.md ASAP
