### ISSUE TITLE
Add cache layer

### ISSUE THREAD

**Issue by JustHumanz** [JustHumanz/Go-Simp#292]
MySQL already fucked with many sql connections, we need a build-cache layer to preventive this 

![Screenshot from 2022-05-03 20-58-32](https://user-images.githubusercontent.com/43176061/166467294-c539c2c0-c77d-4204-89c3-6727e364dead.png)

**Comment by mustafasegf** [comment]
i don't know much about mysql, but we can migrate to postgre and use pgxpool as a connection pooler

**Comment by JustHumanz** [comment]
never heard & experience postgresql before

let me research it first

**Comment by JustHumanz** [comment]
Cache layer already deployed on some services, and the result was ok

CPU usage on mysql has decreasing

![Screenshot from 2022-05-18 00-07-19](https://user-images.githubusercontent.com/43176061/168870985-61ffc9aa-8ba8-441f-adde-aa5a337be581.png)
