### ISSUE TITLE
[BUG] Bilibili return 0

### ISSUE THREAD

**Issue by futag** [JustHumanz/Go-Simp#362]
**Describe the bug**
TotalVideos and ViwersCount in bilibili data return to 0

**Expected behavior**
TotalVideos and ViwersCount in bilibili showing real count 

**Screenshots**
![image](https://user-images.githubusercontent.com/21020026/184500422-fcc8dccc-8f99-4d2c-8621-4f50f27aaf76.png)

**Additional context**

**Comment by JustHumanz** [comment]
I think this just session problem,let me refresh the bilibili session
