### ISSUE TITLE
bilibili reminders show up without tag-me-commanding

### ISSUE THREAD

**Issue by AlzioNever** [JustHumanz/Go-Simp#6]
Seems like bilibili streams are reminded automatically even when no one subscribed them through the bot,
and the already started streams are popping up every 5 minutes.

**Comment by JustHumanz** [comment]
thx for reporting, you right

last night I'm update the bot and not check for live bilibili state,gonna fix it

**Comment by JustHumanz** [comment]
should now fix in [25185fa](https://github.com/JustHumanz/Go-Simp/commit/25185fa2d49cc6dc3d299ac49d9eb5515312f376)
