### ISSUE TITLE
[BUG] Bot is enabled in channel but there hasn't been any stream notifications

### ISSUE THREAD

**Issue by Nekololiphile** [JustHumanz/Go-Simp#71]
**Describe the bug**
I invited the bot to my server and used the command `vtbot>enable live hololive` in a channel and got a confirmation message, but I've yet to see the bot post any stream notifications.

**Expected behavior**
Notifications of new streams and streams that go live.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by JustHumanz** [comment]
Live stream notifications are not sent to your channel because no one user/roles were tagged
you can use `vtbot>tag me hololive` or `vtbot>tag roles {roles name} hololive`

**Comment by Nekololiphile** [comment]
Oh, okay. Is there an option to not have it tag anyone?

**Comment by JustHumanz** [comment]
sadly no but you can make a dummy role and tag that dummy role

**Comment by Nekololiphile** [comment]
Alrighty, thanks for the help, and thanks a lot for a great bot.
